/**
 * FILE NAME: schema.ts
 *
 * ROLE: Defines the Dexie database (tables, indexes, version) and the canonical Transaction / Category / TransactionType types plus the newId() helper.
 *
 * IMPORTANT DEVELOPER DECISIONS ON THIS FILE:
 * ? - Local-first: all app data lives in IndexedDB via Dexie; this is the single source of truth for the schema every other module depends on.
 * ? - Transactions and categories are separate tables; category name (not id) is the join key used by transactions, so renaming must cascade (see repository.ts).
 * ? - Category.icon stores a Tabler icon name string (nullable); colors are stored as CSS color strings, resolved at render time.
 * ? - IDs are UUIDs generated by newId(); createdAt is a Date.now() epoch number.
 *
 * AFFECTS:
 * ! - lib/db/repository.ts (CRITICAL: table definitions, types, and newId are its foundation — changing a column or index breaks every write operation)
 * ! - lib/hooks/useTransactions.ts (CRITICAL: queries `db.transactions` / `db.categories` and exposes the Transaction / Category types to the UI)
 * ? - lib/csv.ts (the CsvRow shape must stay parseable into Transaction)
 * ? - lib/validations/transaction.ts (its inferred input types must match these records)
 * ? - Every view/component that imports the Transaction / Category types
 *
 * AFFECTED BY:
 * ? - Dexie and uuid package versions (upgrades can change index/type behavior)
 *
 * ON FILE EDIT:
 * ! - npm run build (type errors surface anywhere the types are used)
 * ! - npm run lint
 * ? - Bump/verify Dexie version(...) when adding columns, or old installs lose data
 * ? - Verify index fields match the queries in useTransactions.ts
 * * - Adding a required field breaks CSV import, forms, and repository writes — check all
 *
 * AI INSTRUCTIONS
 * - When editing this file, ALWAYS check the AFFECTS list first
 * - After changes, run ALL tests listed under ON FILE EDIT
 * - If AFFECTED BY files change, verify this file still works
 * - KEEP THIS HEADER CURRENT: whenever you edit this file, update ROLE, decisions, AFFECTS, AFFECTED BY, and ON FILE EDIT to match the change
 * - Keep every entry on one line (no wrapped continuations) so Better Comments highlights the full line
 * - Red (!) items are CRITICAL and cannot be skipped
 * - Blue (?) items are important but not blocking
 * - Green (*) items are nice-to-have; skip if not applicable
 */

import Dexie, { type Table } from "dexie";
import { v4 as uuidv4 } from "uuid";

export type TransactionType = "income" | "expense";

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  category: string;
  description: string | null;
  date: string;
  createdAt: number;
}

export interface Category {
  id: string;
  name: string;
  type: TransactionType;
  icon: string | null;
  color: string | null;
}

class DB extends Dexie {
  transactions!: Table<Transaction, string>;
  categories!: Table<Category, string>;

  constructor() {
    super("cash-guard");
    this.version(1).stores({
      transactions: "id, type, category, date, createdAt",
      categories: "id, type, name",
    });
  }
}

export const db = new DB();

export function newId(): string {
  return uuidv4();
}